services:
  - type: web
    name: orbchase-server
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
    plan: free